language: java

os:
  - linux

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_install:
  - jdk_switcher use oraclejdk8
  - java -version

install: true

script:
  - mvn clean test

after_success:
  - mvn clean test jacoco:report coveralls:report


