---
title: "Directory Treemap Viewer"
output: html_notebook
---

Load libraries.

```{r}
library(tidyverse, quietly = T)
library(treemap)
library(data.tree)
```

Read the files in a directory tree.

```{r}
# the path to the directory to be visualized with the treemap
path <- "/home/cesarsv/Documents/papers/2019_papers/jdb-tracer_study_subjects/pdfbox-1.8.16/app/pdfbox-app-1.8.16_original_bundle"
# path <- "/home/cesarsv/Documents/papers/2019_papers/jdb-tracer_study_subjects/pdfbox-1.8.16/app/pdfbox-app-1.8.16_debloated"

# List all the files contained in a directory path
files <- list.files(path = path,
                    pattern = "\\.class$", # consider only class files
                    recursive = TRUE,
                    include.dirs = FALSE)

# Create the data frame of the files, filename column contains the path
df <- data.frame(
  filename = sapply(files,
                    function(fl)
                      paste0("data.tree", "/", fl)),
  file.info(paste(path, files, sep = "/")),
  stringsAsFactors = FALSE
)

# View(df)

```

Convert the data.frame to a data.tree structure.

```{r}
# Create additional columns
df$file <- as.character(rownames(df))
df$pathString <- df$filename

# Convert the dataframe to a data.tree structure
fileStructure <- as.Node(df[,])

# Average left nodes per node
fileStructure$leafCount / (fileStructure$totalCount - fileStructure$leafCount)

# Print an excerpt  of the tree
print(fileStructure, "size", "file", limit = 10)
```

Visualize the tree in a widget.

```{r}
# This requires listviewer, which is available only on github
devtools::install_github("timelyportfolio/listviewer")

# Load listviewer
library(listviewer)

# Convert a data.tree structure to a list-of-list structure
l <- ToListSimple(fileStructure)

# View the lists with 'jsoneditor'
jsonedit(l)
```

Aggregate the results for non-leave nodes

```{r}

# This function sums the nodes that are not leaves 
myApply <- function(node) {
  node$totalSize <- 
    sum(c(node$size, purrr::map_dbl(node$children, myApply)), na.rm = TRUE)
}

# Apply the function to compute the totalSize colum
myApply(fileStructure)

# Print the tree
print(fileStructure, "size", "totalSize", "file", limit = 10)

```

Visualize the treemap.

```{r}

# tree_df <- ToDataFrameTable(fileStructure, "file", "totalSize")
tree_df <- ToDataFrameTypeCol(fileStructure, "file", "totalSize")

# View the data.frame
View(tree_df)

# Size in Kb
tree_df$totalSize <- round(tree_df$totalSize/1024, digits = 1)

# Plot the treemap
treemap(tree_df,
        index=c("level_2", "level_3", "totalSize"),
        vSize="totalSize",
        vColor="totalSize",
        type="value",
        title="",
        title.legend = "size (Kb)",
        range = c(0,80),
        mapping = c(80,40,0))

```

Prune the current treemap to group the small tiles together. 

```{r}
# Sort each node by size
Sort(fileStructure, attribute = "totalSize", decreasing = TRUE, recursive = TRUE)

# The sorted tree now looks like this
print(fileStructure, "size", "totalSize", pruneMethod = "dist", limit = 20)

# Store the original number of nodes for further use
fileStructure$Do(function(x) x$origCount <- x$count)

# This prone function returns 'FALSE' for all nodes that should be combined
# Default is 0.9 of the size of the parent and max of 7 nodes
myPruneFun <- function(x, cutoff = 0.9, maxNodes = 3) {
  if (isNotLeaf(x)) return (TRUE)
  if (x$position > maxNodes) return (FALSE)
  return (x$totalSize < (x$parent$totalSize * cutoff))
}

# Clone the tree, because we might want to play around with different parameters
treeClone <- Clone(fileStructure, pruneFun = myPruneFun)

# Print the pruned tree
print(treeClone, "level", "totalSize", "count", "origCount", "position", pruneMethod = "simple")

# Sum nodes that we pruned away into a new node called "Other" 
treeClone$Do(
  function(x) {
    if (is.na(x) == F) {
      missing <-
        x$totalSize - sum(sapply(x$children, function(x)
          x$totalSize))
      other <- x$AddChild(paste0("Other(", x$origCount, ")"))
      # other$file <- paste0("Other(", x$origCount, ")")
      # other$country <- "Other"
      # other$continent <- x$name
      # other$GNI <- 0
      other$totalSize <- missing
    }
  }
  ,
  filterFun = function(x)
    x$level == 3
)

print(treeClone, "totalSize", pruneMethod = "simple", limit = 20)

# Plot the treemap
treeClone_df <- ToDataFrameTypeCol(treeClone, "file", "totalSize", "level")

# View the data.frame
View(treeClone_df)

# Size in Kb
treeClone_df$totalSize <- round(treeClone_df$totalSize/1024, digits = 1)

# Plot the treemap
treemap(treeClone_df,
        index=c("level_2", "level_3", "totalSize"),
        vSize="totalSize",
        vColor="totalSize",
        type="value",
        title="",
        title.legend = "size (Kb)",
        range = c(0,80),
        mapping = c(80,40,0))

```


Plot as a dendogram

```{r}

plot(as.dendrogram(treeClone, heightAttribute = "totalSize"))

```

