name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ ubuntu-latest ]
        java: [ 11 ]
    runs-on: ${{ matrix.os }}
    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: "Cache Local Maven Repository"
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
#      - name: "CheckStyle"
#        run: mvn validate --errors
      - name: "Compile and Install"
        run: mvn clean install -DskipTests --errors
      - name: "Unit Tests"
        run: mvn test --errors --fail-at-end
#      - name: "Integration Tests"
#        run: mvn failsafe:integration-test --errors --fail-at-end
        # The following is only executed on Ubuntu on Java 11
      - name: "JaCoCo Coverage Report"
        if: matrix.os == 'ubuntu-latest' && matrix.java == 11 && github.repository == 'castor-software/jdbl'
        run: mvn jacoco:report
      - name: "Codecov"
        if: matrix.os == 'ubuntu-latest' && matrix.java == 11 && github.repository == 'castor-software/jdbl'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./jdbl-core/target/site/jacoco/jacoco.xml
          flags: unittests
      - name: "Cache SonarCloud"
        if: matrix.os == 'ubuntu-latest' && matrix.java == 11 && github.repository == 'castor-software/jdbl'
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: "SonarCloud"
        if: matrix.os == 'ubuntu-latest' && matrix.java == 11 && github.repository == 'castor-software/jdbl'
        run: mvn sonar:sonar -Dsonar.projectKey=castor-software_jdbl -Dsonar.organization=castor-software -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.java.source=11 -Dsonar.java.target=11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}